name       : qt5-wayland
version    : 5.12.1
release    : 15
source     :
    - https://download.qt.io/official_releases/qt/5.12/5.12.1/submodules/qtwayland-everywhere-src-5.12.1.tar.xz : 88f0507628b3697b0d59349d27b5e60a313a3138927722d6cf981089fff02553
license    :
    - LGPL-2.1
    - LGPL-3.0
    - GFDL-1.3
    - GPL-3.0
component  : desktop.qt
summary    : Qt 5 Wayland Library
description: |
    QtWayland is a Qt 5 module that wraps the functionality of Wayland. QtWayland
    is separated into a client and server side. The client side is the wayland
    platform plugin, and provides a way to run Qt applications as Wayland clients.
    The server side is the QtCompositor API, and allows users to write their
    own Wayland compositors.
builddeps  :
    - pkgconfig(fontconfig)
    - pkgconfig(freetype2)
    - pkgconfig(gl)
    - pkgconfig(libinput)
    - pkgconfig(Qt5Quick)
    - pkgconfig(wayland-egl)
    - pkgconfig(wayland-scanner)
    - pkgconfig(xkbcommon)
    - pkgconfig(xcomposite)
    - pkgconfig(xi)
    - pkgconfig(xrender)
patterns   :
    - demos : /usr/lib64/qt5/examples
    - devel :
        - /usr/bin
setup      : |
    %qmake CONFIG+="release wayland-compositor" qtwayland.pro
build      : |
    %make
install    : |
    %make_install INSTALL_ROOT=$installdir
